kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gcptest
spec:
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: gcptest
    spec:
      containers:
      - name: frontend
        image: baswerc/gcptest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080